---

- hosts: all
  become: yes
  tasks:
  - name: yum update
    yum:
      name: "*"
      state: latest

- hosts: all
  become: yes
  tasks:
  - block:
    - name: Installing nginx
      yum:
        name: nginx
        state: present

    - name: "Restart nginx"
      systemd:
        name: nginx
        daemon_reload: true
        state: started
        enabled: true

    - name: Flush handlers
      meta: flush_handlers

    - name: Get services status
      ansible.builtin.service_facts:

    - name: Check if nginx.service is running
      ansible.builtin.assert:
        quiet: true
        that: ansible_facts.services['nginx.service']['state'] == 'running'
        fail_msg: nginx.service is not running